#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE $HYDRA_DB;
  CREATE USER $HYDRA_USER WITH ENCRYPTED PASSWORD '$HYDRA_PASS';
  GRANT ALL PRIVILEGES ON DATABASE $HYDRA_DB TO $HYDRA_USER;

  CREATE DATABASE $KRATOS_DB;
  CREATE USER $KRATOS_USER WITH ENCRYPTED PASSWORD '$KRATOS_PASS';
  GRANT ALL PRIVILEGES ON DATABASE $KRATOS_DB TO $KRATOS_USER;
EOSQL
